### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by KarishmaVanwari** [parthpanchal123/antariksh#12]
Adding a custom scrollbar would improve the look of the website.

**Comment by KarishmaVanwari** [comment]
Hey @parthpanchal123 can I work on this for Hacktoberfest 2021? You can let me know your colour preferences, if any.

**Comment by parthpanchal123** [comment]
Black probably

**Comment by KarishmaVanwari** [comment]
> Black probably

I too thought the same. Please add hacktoberfest label and assign me.

**Comment by KarishmaVanwari** [comment]
@parthpanchal123 do have a look at #15
