### ISSUE TITLE
Make screenshots better

### ISSUE THREAD

**Issue by gouravkhunger** [parthpanchal123/antariksh#13]
Hey, as you said I am ready to contribute screenshot previews to the repo.

Can you please choose from the below two, which ones do you want to have in your repo?

Safari:
<img width="1392" alt="Screenshot 2021-10-03 at 6 31 38 PM" src="https://user-images.githubusercontent.com/46792249/135754880-970ebee1-7782-4bfe-b52e-dc158d835a5f.png">

Brave:
<img width="1392" alt="Screenshot 2021-10-03 at 6 31 19 PM" src="https://user-images.githubusercontent.com/46792249/135754892-0851c696-48da-47ee-b13d-9b4798fa8b77.png">

And sorry, I forgot to unpin the extensions from Brave, if you choose brave I can disable them for once so that the top bar is clean.

**Comment by parthpanchal123** [comment]
Lets go with the brave one 💯

**Comment by gouravkhunger** [comment]
Sure, I am disabling the extensions for now and taking the ss :)

**Comment by gouravkhunger** [comment]
@parthpanchal123 Made the PR :)
