### ISSUE TITLE
Avoid overlapping of iotd image over header

### ISSUE THREAD

**Issue by KarishmaVanwari** [parthpanchal123/antariksh#16]
![antariksh-ss](https://user-images.githubusercontent.com/78212650/135806714-c82d5707-a388-4fab-a4d1-e636d16da3c1.PNG)

overlapping of image and go back on the header must be avoided.

**Comment by KarishmaVanwari** [comment]
Hey @parthpanchal123 , I would like to work on this issue for Hacktoberfest 2021, if it seems okay.

**Comment by parthpanchal123** [comment]
@KarishmaVanwari Nice catch , Go ahead

**Comment by KarishmaVanwari** [comment]
@parthpanchal123 have a look at #17
