### ISSUE TITLE
Show a loading indicator when the images are loading .

### ISSUE THREAD

**Issue by parthpanchal123** [parthpanchal123/antariksh#2]

**Comment by Xaconi** [comment]
hey @parthpanchal123 can I grab this one?

**Comment by parthpanchal123** [comment]
@Xaconi Go ahead  💯

**Comment by parthpanchal123** [comment]
@Xaconi The loading animation looks very :cool: . Thank you very much for your contribution :+1: Appreciate it :100:

**Comment by parthpanchal123** [comment]
@Xaconi The loading animation is working fine, but now we cant click on the individual image and open up its info.

**Comment by Xaconi** [comment]
> @Xaconi The loading animation is working fine, but now we cant click on the individual image and open up its info. Edit : It was a small bug , I fixed that 😄

Thanks for that!

 ![](https://media3.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)
