### ISSUE TITLE
Show  a placeholder when no images are returned 

### ISSUE THREAD

**Issue by parthpanchal123** [parthpanchal123/antariksh#20]
![image](https://user-images.githubusercontent.com/20091596/135846099-68cc4978-0f3f-4c60-a95c-4b1fa2e7f483.png)

Currently, nothing is shown when the API does not return anything . Show some animated gif or an animated image saying that No images were found for that search term.

If the image or the gif would be related to space, it would be awesome.

**Comment by Shubh-2402** [comment]
hey @parthpanchal123  i would like to work on this issue . Plz assign it to me

**Comment by parthpanchal123** [comment]
@Shubh-2402 @error434 is already working on this issue , meanwhile you can explore the project and point out any new issues  if you find them :)

**Comment by error434** [comment]
this can now be closed right?
