### ISSUE TITLE
Add a Contributing.md file 

### ISSUE THREAD

**Issue by parthpanchal123** [parthpanchal123/antariksh#3]
Currently , there is no contributing.md file in the repo

**Comment by roshaan005** [comment]
Can I work on this one?

**Comment by parth-panchal** [comment]
I would love to work on this. Can you please assign this issue to me?

**Comment by parthpanchal123** [comment]
@roshaan005 go ahead and work on this :) Good luck !

**Comment by parthpanchal123** [comment]
@parthpanchal123 Feel free to check other issues or create one!

**Comment by parthpanchal123** [comment]
@parth-panchal Feel free to check other issue or create new if you find any :)

**Comment by roshaan005** [comment]
could you please add the hacktoberfest label to this?

**Comment by parthpanchal123** [comment]
Thanks @roshaan005 for your contribution :+1:
