### ISSUE TITLE
Open Image of day in a new tab

### ISSUE THREAD

**Issue by KarishmaVanwari** [parthpanchal123/antariksh#5]
To enhance user experience, I think the image of the day, when clicked, should be opened in a new tab.

**Comment by KarishmaVanwari** [comment]
Can I work on this as a part of Hacktoberfest 2021 ? @parthpanchal123

**Comment by parthpanchal123** [comment]
@KarishmaVanwari Go ahead 👍

**Comment by KarishmaVanwari** [comment]
Could you add hacktoberfest label and assign it to me ? @parthpanchal123

**Comment by KarishmaVanwari** [comment]
![antariksh](https://user-images.githubusercontent.com/78212650/135744949-22128ee8-01be-4c7f-acb8-427c6fb53924.PNG)

Hey @parthpanchal123 , can you help me figure out why does it show like this, even though the network connection is proper?

**Comment by parthpanchal123** [comment]
@KarishmaVanwari Just pull the latest code from the repo

**Comment by KarishmaVanwari** [comment]
> @KarishmaVanwari Just pull the latest code from the repo

It is already up to date.

**Comment by parthpanchal123** [comment]
Did you check the browser console for logs?

**Comment by KarishmaVanwari** [comment]
Yup, it's empty

**Comment by parthpanchal123** [comment]
You are using npm or yarn ?

**Comment by KarishmaVanwari** [comment]
npm

**Comment by parthpanchal123** [comment]
just run npm to install any missing dependencies

**Comment by KarishmaVanwari** [comment]
I did that, but still shows the same

**Comment by parthpanchal123** [comment]
Is it showing this on all pages or just iotd ?

**Comment by KarishmaVanwari** [comment]
Only on iotd

**Comment by KarishmaVanwari** [comment]
Do I have to add an api key in .env file?

**Comment by parthpanchal123** [comment]
Yes or else it wont work

**Comment by KarishmaVanwari** [comment]
Is it so only for iotd page?

**Comment by parthpanchal123** [comment]
Yes for some API requests , it need an API key . Hence the IOTD req wont work without an API key

**Comment by KarishmaVanwari** [comment]
Ohh okay, thank you. I'll do that.

**Comment by KarishmaVanwari** [comment]
@parthpanchal123 please have a look at #11
