### ISSUE TITLE
Add a scroll to top shortcut !

### ISSUE THREAD

**Issue by parthpanchal123** [parthpanchal123/antariksh#7]
![image](https://user-images.githubusercontent.com/20091596/135740403-bf77aa2d-38c7-497b-a589-07e6fb7dffd7.png)

Currently , there is no scroll to top shortcut . Add it on the above page

**Comment by Abhishek07-0302** [comment]
I would like to work on this. Kindly assign me if available.

**Comment by kavin25** [comment]
Please go through #8
