### ISSUE TITLE
UI(go back button)

### ISSUE THREAD

**Issue by aniketnegii** [parthpanchal123/antariksh#9]
The UI of the go back button can be made similar to the launch button and we can use an arrow instead of a rocket.
![Screenshot 2021-10-03 114936](https://user-images.githubusercontent.com/60145485/135742533-0b62906b-1670-4fef-9793-781fa668e0e2.png)

**Comment by parthpanchal123** [comment]
Since I wanted to keep the space theme , hence I added the rocket instead of something else :)

**Comment by aniketnegii** [comment]
I was talking about the icon for the go-back button. The icon for launch is perfect.
